"""Data schemas for Phase 4 — Outcome Verifier & Recovery Engine.

Defines strongly-typed result objects passed between the verifier,
failure classifier, and recovery engine so the LangGraph orchestrator
can route state transitions deterministically.
"""

from enum import Enum
from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Failure Mode Taxonomy
# ---------------------------------------------------------------------------

class FailureMode(str, Enum):
    """Enumeration of all recognized failure patterns the verifier can detect.

    Each mode maps to a specific recovery strategy in RecoveryEngine.
    """
    # No failure — action executed and state changed as expected
    NONE = "none"

    # Screen did not visually change at all — action likely missed
    NO_VISUAL_CHANGE = "no_visual_change"

    # UI rendered but changed less than threshold — partial update (e.g. loading)
    UI_LAG = "ui_lag"

    # Element click registered but wrong element changed (adjacent mis-click)
    MISSED_CLICK = "missed_click"

    # An unexpected modal / dialog / alert is now blocking the UI
    MODAL_BLOCKED = "modal_blocked"

    # Typed text did not appear in the expected field
    TYPE_FAILED = "type_failed"

    # Browser navigation failed (404, network error, redirect loop)
    NAVIGATION_ERROR = "navigation_error"

    # Application did not appear or launch after APP_OPEN
    APP_LAUNCH_FAILED = "app_launch_failed"

    # Maximum retry attempts exhausted — agent must abort
    MAX_RETRIES_EXCEEDED = "max_retries_exceeded"

    # Could not determine what happened (ambiguous diff)
    UNKNOWN = "unknown"


# ---------------------------------------------------------------------------
# Verification Result
# ---------------------------------------------------------------------------

class VerificationResult(BaseModel):
    """Result produced by OutcomeVerifier after evaluating a single step.

    Returned to the LangGraph controller to decide the next state transition:
    - passed=True   → proceed to next step
    - passed=False  → enter recovery branch with failure_mode and details
    """

    passed: bool
    """True if the action outcome was verified successfully."""

    failure_mode: FailureMode = FailureMode.NONE
    """Classified failure mode when passed=False."""

    visual_diff_score: float = 0.0
    """Perceptual pixel-change ratio between pre and post screenshots (0.0 – 1.0).
    Higher value means more visual change occurred."""

    element_delta_count: int = 0
    """Number of UIElement IDs that appeared or disappeared between states."""

    details: str = ""
    """Human-readable explanation of the verification outcome."""

    retry_count: int = 0
    """How many recovery retries have been attempted for this step so far."""

    metadata: Dict[str, Any] = Field(default_factory=dict)
    """Additional diagnostic data (e.g. phash distance, changed element IDs)."""


# ---------------------------------------------------------------------------
# Recovery Plan
# ---------------------------------------------------------------------------

class RecoveryStep(BaseModel):
    """A single corrective action to be injected into the execution pipeline."""

    action_type: str
    """Action type string matching ActionType enum (e.g. 'wait', 'press', 'click')."""

    params: Dict[str, Any] = Field(default_factory=dict)
    """Parameters for the action (e.g. {'seconds': 2.0} or {'key': 'escape'})."""

    reason: str = ""
    """Why this recovery step was chosen."""


class RecoveryPlan(BaseModel):
    """Ordered list of recovery steps generated by RecoveryEngine.

    The LangGraph orchestrator injects these steps ahead of the next
    planning cycle so the planner receives a more stable UIState.
    """

    failure_mode: FailureMode
    """The failure mode that triggered this recovery plan."""

    steps: List[RecoveryStep] = Field(default_factory=list)
    """Ordered corrective actions to execute before replanning."""

    should_replan: bool = True
    """If True, invoke the Hierarchical Planner again after recovery steps."""

    should_abort: bool = False
    """If True, the task should be aborted (max retries exceeded or unrecoverable)."""

    explanation: str = ""
    """Natural language explanation of the recovery strategy chosen."""
