"""SIVAC - Self-Improving Vision Agent for Autonomous Computer Use."""
from .perception import HybridPerceptionEngine, UIState, UIElement, BBox
from .model import ModelFactory
from .actions import (
    ActionType,
    ActionCommand,
    ActionResult,
    ActionSafetyGuard,
    EmergencyStopMonitor,
    ActionExecutor,
)
from .verifier import (
    VerificationResult,
    FailureMode,
    RecoveryPlan,
    RecoveryStep,
    VisualDiffEngine,
    StateDiffEngine,
    FailureClassifier,
    RecoveryEngine,
    OutcomeVerifier,
)
from .memory import (
    TaskStatus,
    TaskRecord,
    TrajectoryRecord,
    StepRecord,
    VerificationRecord,
    LearnedSkill,
    SimilarTaskResult,
    HeuristicQueryResult,
    RetrievedExperience,
    DatabaseManager,
    ChromaVectorStore,
    EpisodicMemoryManager,
    SemanticMemoryManager,
    ExperienceRetriever,
)
from .agent import (
    AgentState,
    create_initial_state,
    HierarchicalPlanner,
    AgentNodes,
    build_agent_graph,
    SIVACAgent,
)
from .learning import (
    TrajectoryEvaluation,
    ExtractedLesson,
    ReflectionOutput,
    TrajectoryEvaluator,
    ReflectionEngine,
    LessonExtractor,
    StrategyManager,
    SelfImprovementPipeline,
)

__version__ = "0.1.0"

__all__ = [
    "HybridPerceptionEngine",
    "UIState",
    "UIElement",
    "BBox",
    "ModelFactory",
    "ActionType",
    "ActionCommand",
    "ActionResult",
    "ActionSafetyGuard",
    "EmergencyStopMonitor",
    "ActionExecutor",
    "VerificationResult",
    "FailureMode",
    "RecoveryPlan",
    "RecoveryStep",
    "VisualDiffEngine",
    "StateDiffEngine",
    "FailureClassifier",
    "RecoveryEngine",
    "OutcomeVerifier",
    "TaskStatus",
    "TaskRecord",
    "TrajectoryRecord",
    "StepRecord",
    "VerificationRecord",
    "LearnedSkill",
    "SimilarTaskResult",
    "HeuristicQueryResult",
    "RetrievedExperience",
    "DatabaseManager",
    "ChromaVectorStore",
    "EpisodicMemoryManager",
    "SemanticMemoryManager",
    "ExperienceRetriever",
    "AgentState",
    "create_initial_state",
    "HierarchicalPlanner",
    "AgentNodes",
    "build_agent_graph",
    "SIVACAgent",
    "TrajectoryEvaluation",
    "ExtractedLesson",
    "ReflectionOutput",
    "TrajectoryEvaluator",
    "ReflectionEngine",
    "LessonExtractor",
    "StrategyManager",
    "SelfImprovementPipeline",
]
